In [1]:
import numpy as np

# Array Basics


In [2]:
fruits = ['apple', 'banana', 'cherry', 'date']


In [3]:
arr1 = np.array(fruits)
print(arr1)

['apple' 'banana' 'cherry' 'date']


In [4]:
print(arr1.dtype)
# arr1 is datatype U6  u means the integers are unsigned. 6 means they are stored in 6 bis

<U6


In [5]:
arr_2 = np.array([(10, 11, 12),(13, 14, 15)])
print(arr_2)

[[10 11 12]
 [13 14 15]]


In [6]:
print(arr_2.T)
# this does not change the value of arr_2 it will just print the the transposed version of arr_2

[[10 13]
 [11 14]
 [12 15]]


In [8]:
#Create a variable named arr_3 as a two-dimensional array containing  
#(1, 3, 5) and (2, 4, 6) then print arr_3.

arr_3 = np.array([(1, 3, 5),(2 , 4, 6)])
print(arr_3)

[[1 3 5]
 [2 4 6]]


In [9]:
print(arr_3.ndim)

2


In [11]:
# Create a variable named arr_4 as a one-dimensional array containing two values: 
# using slicing notation, the element of arr_3 at index position 0, 2 and the element 
# of arr_3 at index position 1, 1. Then print arr_4.

arr_4 = np.array([arr_3[0][2], arr_3[1][1]])
print(arr_4)

[5 4]


In [20]:
# Create a variable named arr_5 as a three-dimensional array containing all 1’s, 
# with two values in each dimension. Then print arr_5.
arr_5 = np.array([[[1, 1],[1,1]],[[1, 1],[1, 1]]])
print(arr_5)

[[[1 1]
  [1 1]]

 [[1 1]
  [1 1]]]
